# Generated by Django 2.0.6 on 2018-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_title', models.CharField(max_length=255)),
                ('question_text', models.CharField(max_length=255)),
                ('question_answer', models.CharField(max_length=255)),
                ('question_hint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
